/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MiningState = IDL.Variant({
  'notStarted' : IDL.Null,
  'active' : IDL.Null,
  'expired' : IDL.Null,
});
export const MiningTask = IDL.Record({
  'startTime' : IDL.Int,
  'duration' : IDL.Nat,
  'user' : IDL.Principal,
  'state' : MiningState,
});
export const TransactionState = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Amount = IDL.Nat;
export const Wallet = IDL.Text;
export const Transaction = IDL.Record({
  'user' : IDL.Principal,
  'state' : TransactionState,
  'amount' : Amount,
  'toWallet' : Wallet,
});
export const RichUserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'balance' : Amount,
  'telegramFollowed' : IDL.Bool,
  'wallet' : Wallet,
  'miningCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'balance' : Amount,
  'telegramFollowed' : IDL.Bool,
  'wallet' : Wallet,
  'miningCount' : IDL.Nat,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveWithdrawal' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllMiningTasks' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, MiningTask))],
      ['query'],
    ),
  'getAllTransactions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Transaction))],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(RichUserProfile)], ['query']),
  'getBalances' : IDL.Func([], [Amount], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMiningTasks' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, MiningTask))],
      ['query'],
    ),
  'getTelegramLink' : IDL.Func([], [IDL.Text], ['query']),
  'getTransactions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Transaction))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'linkTelegram' : IDL.Func([], [IDL.Bool], []),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'rejectWithdrawal' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'requestApproval' : IDL.Func([], [], []),
  'requestWithdrawal' : IDL.Func([IDL.Text, Amount], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'startMining' : IDL.Func([IDL.Nat], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MiningState = IDL.Variant({
    'notStarted' : IDL.Null,
    'active' : IDL.Null,
    'expired' : IDL.Null,
  });
  const MiningTask = IDL.Record({
    'startTime' : IDL.Int,
    'duration' : IDL.Nat,
    'user' : IDL.Principal,
    'state' : MiningState,
  });
  const TransactionState = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Amount = IDL.Nat;
  const Wallet = IDL.Text;
  const Transaction = IDL.Record({
    'user' : IDL.Principal,
    'state' : TransactionState,
    'amount' : Amount,
    'toWallet' : Wallet,
  });
  const RichUserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'balance' : Amount,
    'telegramFollowed' : IDL.Bool,
    'wallet' : Wallet,
    'miningCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'balance' : Amount,
    'telegramFollowed' : IDL.Bool,
    'wallet' : Wallet,
    'miningCount' : IDL.Nat,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveWithdrawal' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllMiningTasks' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, MiningTask))],
        ['query'],
      ),
    'getAllTransactions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Transaction))],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(RichUserProfile)], ['query']),
    'getBalances' : IDL.Func([], [Amount], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMiningTasks' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, MiningTask))],
        ['query'],
      ),
    'getTelegramLink' : IDL.Func([], [IDL.Text], ['query']),
    'getTransactions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Transaction))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'linkTelegram' : IDL.Func([], [IDL.Bool], []),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'rejectWithdrawal' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'requestApproval' : IDL.Func([], [], []),
    'requestWithdrawal' : IDL.Func([IDL.Text, Amount], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'startMining' : IDL.Func([IDL.Nat], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };