/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Amount = bigint;
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type MiningState = { 'notStarted' : null } |
  { 'active' : null } |
  { 'expired' : null };
export interface MiningTask {
  'startTime' : bigint,
  'duration' : bigint,
  'user' : Principal,
  'state' : MiningState,
}
export interface RichUserProfile {
  'principal' : Principal,
  'balance' : Amount,
  'telegramFollowed' : boolean,
  'wallet' : Wallet,
  'miningCount' : bigint,
}
export interface Transaction {
  'user' : Principal,
  'state' : TransactionState,
  'amount' : Amount,
  'toWallet' : Wallet,
}
export type TransactionState = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'balance' : Amount,
  'telegramFollowed' : boolean,
  'wallet' : Wallet,
  'miningCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Wallet = string;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveWithdrawal' : ActorMethod<[bigint], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllMiningTasks' : ActorMethod<[], Array<[bigint, MiningTask]>>,
  'getAllTransactions' : ActorMethod<[], Array<[bigint, Transaction]>>,
  'getAllUserProfiles' : ActorMethod<[], Array<RichUserProfile>>,
  'getBalances' : ActorMethod<[], Amount>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMiningTasks' : ActorMethod<[], Array<[bigint, MiningTask]>>,
  'getTelegramLink' : ActorMethod<[], string>,
  'getTransactions' : ActorMethod<[], Array<[bigint, Transaction]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'linkTelegram' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'rejectWithdrawal' : ActorMethod<[bigint], string>,
  'requestApproval' : ActorMethod<[], undefined>,
  'requestWithdrawal' : ActorMethod<[string, Amount], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'startMining' : ActorMethod<[bigint], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];